version: '3.4'

services:
  mysql:
    image: mysql:8.0.22

  template_api:
    image: ${DOCKER_REGISTRY-}templatehost
    build:
      context: .
      dockerfile: Template.Host/Dockerfile

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.1  

  sonarqube:
    image: sonarqube:latest

volumes:
  templatedb:
  elasticsearch-data:
networks:
  template-network:
    driver: bridge
  elasticnetwork:
    driver: bridge